name: ArmorWeight
version: 0.3.5
description: Armor has a weight now!
author: Zettelkasten
main: com.zettelnet.armorweight.ArmorWeightPlugin
website: http://dev.bukkit.org/bukkit-plugins/armorweight/

commands:
  weight:
    description: Displays your current weight
    usage: /weight [help]
  armorweight:
    descriptions: Displays information about ArmorWeight
    usage: /armorweight [help]
    aliases: [armourweight]

permissions:
  armorweight.*:
    description: Gives access to all ArmorWeight permissions
    children:
      armorweight.weight*: true
      armorweight.effect.*: true
  armorweight.weight.*:
    description: Enables all weight influenceing factors
    children:
      armorweight.weight.armor: true
  armorweight.weight.armor:
    description: Makes your weight be changed by armor
    default: true
  armorweight.effect.*:
    description: Enables all effects accociated with weight
    children:
      armorweight.effect.speed: true
  armorweight.effect.speed:
    description: Makes your movement speed change depending on your weight
    default: true
  armorweight.command.*:
    description: Gives access to all ArmorWeight commands
    children:
      armorweight.command.weight.*: true
      armorweight.command.plugin.*: true
  armorweight.command.weight.*:
    description: Gives access to the full /weight command
    children:
      armorweight.command.weight.getown: true
      armorweight.command.weight.getothers: true
  armorweight.command.weight.getown:
    description: Allows you to display your current weight
    default: true
  armorweight.command.weight.getothers:
    description: Allows you to display the current weight of other players
    default: op
  armorweight.command.plugin.*:
    description: Gives access to the full /armorweight command
    children:
      armorweight.command.plugin.info: true
      armorweight.command.plugin.reload: true
  armorweight.command.plugin.info:
    description: Displays information about ArmorWeight
    default: true
  armorweight.command.plugin.reload:
    description: Allows you to reload the configurations of ArmorWeight
    default: op
